"""Phase 5 — deterministic APDL deck emission from the IR.

The deck is a *preprocessing-only* model: element types, materials, sections,
geometry, mesh, and boundary conditions. No /SOLU, load case, or /POST1
commands are emitted; the optional PyMAPDL verification pass (Phase 6) issues
its own solves against a live session instead.

Design rules (each closes a legacy weakness):
  - every number is written from the IR exactly once; comments cite provenance
  - mesh size / tolerances are *SET parameters, not literals
  - attributes are applied through explicit entity selection, never through
    the order-sensitive LATT-then-LMESH,ALL idiom
  - supports select CM components built from tracked entity ids, never
    coordinate-window NSEL boxes
  - a NUMMRG safety net runs after meshing at the model merge tolerance
  - the axis permutation (IFC Z-up -> APDL frame) happens in exactly one
    function, documented in the deck header
"""

from __future__ import annotations

import math
import re
from pathlib import Path

from ..config import ConversionConfig
from ..model.ir import AnalyticalModel, Member1D

Vec3 = tuple[float, float, float]


def _cm_name(prefix: str, raw: str) -> str:
    """Sanitize to a legal APDL component name (alnum/underscore, <=32)."""
    s = re.sub(r"[^A-Za-z0-9_]", "_", raw)
    return (prefix + s)[:32]


class DeckWriter:
    def __init__(self, model: AnalyticalModel, config: ConversionConfig):
        self.m = model
        self.cfg = config
        self.lines_out: list[str] = []
        self.line_no = 0
        self.area_no = 0
        #: straight-line registry: (kp_lo, kp_hi) -> APDL line number, mirroring
        #: APDL's own reuse of an existing line between two keypoints
        self.line_of: dict[tuple[int, int], int] = {}
        self.extra_kp = len(model.nodes)         # orientation / arc-center keypoints
        self.member_line: dict[int, int] = {}    # member id -> line number
        self.surface_area: dict[int, int] = {}   # surface id -> area number

    # -- infrastructure -------------------------------------------------------

    def w(self, *rows: str) -> None:
        self.lines_out.extend(rows)

    def p(self, v: Vec3) -> tuple[float, float, float]:
        """Axis permutation + rounding — the single coordinate-frame gate."""
        d = self.cfg.coordinate_decimals
        x, y, z = (round(c, d) for c in v)
        if self.cfg.vertical_axis == "y":
            return (x, z, y)                     # IFC Z-up -> APDL Y vertical
        return (x, y, z)

    def _new_kp(self, v: Vec3) -> int:
        self.extra_kp += 1
        x, y, z = self.p(v)
        self.w(f"K,{self.extra_kp},{x:g},{y:g},{z:g}")
        return self.extra_kp

    def _line(self, k1: int, k2: int) -> int:
        key = (min(k1, k2), max(k1, k2))
        if key in self.line_of:
            return self.line_of[key]
        self.w(f"L,{k1},{k2}")
        self.line_no += 1
        self.line_of[key] = self.line_no
        return self.line_no

    # -- sections of the deck -------------------------------------------------

    def header(self) -> None:
        m = self.m
        vert = "Y" if self.cfg.vertical_axis == "y" else "Z"
        self.w(
            "FINISH",
            "/CLEAR,NOSTART",
            f"/TITLE,{m.name} converted from {Path(str(m.meta.get('source',''))).name}",
            f"/COM, generated by ifc_to_apdl - domain: {m.domain}",
            "/COM, units: m, kg, s, Pa (SI)",
            f"/COM, frame: IFC Z-up emitted with APDL {vert} vertical",
            "/PREP7",
            f"*SET,MESH_SIZE,{self.cfg.mesh.target_size:g}",
            f"*SET,MERGE_TOL,{m.meta.get('merge_tol', 1e-4):g}",
            "",
        )

    def element_types(self) -> dict[str, int]:
        used: list[str] = []
        for coll in (self.m.members, self.m.surfaces, self.m.volumes):
            for obj in coll:
                if obj.etype not in used:
                    used.append(obj.etype)
        if self.m.links and "COMBIN14" not in used:
            used.append("COMBIN14")
        if self.m.masses and "MASS21" not in used:
            used.append("MASS21")
        type_of = {et: i + 1 for i, et in enumerate(used)}
        for et, tid in type_of.items():
            self.w(f"ET,{tid},{et}")
            if et == "PIPE288":
                self.w(f"KEYOPT,{tid},3,3   ! cubic shape functions")
        self.w("")
        return type_of

    def materials(self) -> None:
        for mid, mat in sorted(self.m.materials.items()):
            conf = f", confidence {mat.confidence:.2f}" if mat.confidence is not None else ""
            self.w(f"/COM, material {mid}: {mat.name} [{mat.source}{conf}]")
            if mat.flagged:
                reason = next((n for n in mat.notes
                               if n.startswith(("out-of-scope family",
                                                "no material association"))),
                              "retrieval below threshold")
                self.w(f"/COM, *** FLAGGED FOR ENGINEER REVIEW - {reason} ***")
            self.w(
                f"MP,EX,{mid},{mat.elastic_modulus:g}",
                f"MP,PRXY,{mid},{mat.poisson_ratio:g}",
                f"MP,DENS,{mid},{mat.density:g}",
            )
        self.w("")

    def sections(self) -> None:
        for sid, sec in sorted(self.m.sections.items()):
            self.w(*sec.apdl())
            self.w(*sec.apdl_offset())
        self.w("")

    def keypoints(self) -> None:
        for kid, v in self.m.nodes.items():
            x, y, z = self.p(v)
            self.w(f"K,{kid},{x:g},{y:g},{z:g}")
        self.w("")

    def members(self, type_of: dict[str, int]) -> None:
        m = self.m
        by_class: dict[str, list[int]] = {}
        for mem in m.members:
            self.w(f"/COM, {mem.prov.guid} - {mem.prov.ifc_class} '{mem.prov.name}'")
            if mem.arc is not None:
                kc = self._new_kp(mem.arc.center)
                self.w(f"LARC,{mem.start},{mem.end},{kc},{round(mem.arc.radius, 6):g}")
                self.line_no += 1
                ln = self.line_of[(min(mem.start, mem.end), max(mem.start, mem.end))] = self.line_no
            else:
                ln = self._line(mem.start, mem.end)
            self.member_line[mem.id] = ln
            korient = ""
            if mem.etype == "BEAM188":
                korient = str(self._orientation_kp(mem))
            self.w(
                f"LSEL,S,LINE,,{ln}",
                f"LATT,{mem.material},,{type_of[mem.etype]},,{korient},,{mem.section}",
            )
            by_class.setdefault(mem.prov.ifc_class, []).append(ln)
        self.w("LSEL,ALL", "")
        self._entity_cms(by_class, "LINE")

    def _orientation_kp(self, mem: Member1D) -> int:
        p1 = self.m.nodes.xyz(mem.start)
        p2 = self.m.nodes.xyz(mem.end)
        d = tuple((b - a) for a, b in zip(p1, p2))
        n = math.sqrt(sum(c * c for c in d))
        d = tuple(c / n for c in d)
        mid = tuple((a + b) / 2 for a, b in zip(p1, p2))
        # orientation point: vertical offset unless the member is vertical
        if abs(d[2]) < 0.9:
            o = (mid[0], mid[1], mid[2] + 1.0)
        else:
            o = (mid[0] + 1.0, mid[1], mid[2])
        return self._new_kp(o)

    def surfaces(self, type_of: dict[str, int]) -> None:
        by_class: dict[str, list[int]] = {}
        for surf in self.m.surfaces:
            self.w(f"/COM, {surf.prov.guid} - {surf.prov.ifc_class} '{surf.prov.name}'")
            loop = surf.loop
            # pre-create boundary lines through the registry so shared edges
            # (slab edge on a beam axis) reuse the beam's line
            lns = [self._line(loop[i], loop[(i + 1) % len(loop)]) for i in range(len(loop))]
            if len(lns) <= 10:
                self.w("AL," + ",".join(str(ln) for ln in lns))
            else:
                # AL takes at most 10 line arguments; select-then-AL,ALL scales
                self.w("LSEL,NONE")
                for ln in lns:
                    self.w(f"LSEL,A,LINE,,{ln}")
                self.w("AL,ALL", "LSEL,ALL")
            self.area_no += 1
            self.surface_area[surf.id] = self.area_no
            self.w(
                f"ASEL,S,AREA,,{self.area_no}",
                f"AATT,{surf.material},,{type_of[surf.etype]},,{surf.section}",
            )
            by_class.setdefault(surf.prov.ifc_class, []).append(self.area_no)
        self.w("ASEL,ALL", "")
        self._entity_cms(by_class, "AREA")

    def volumes(self, type_of: dict[str, int]) -> None:
        if not self.m.volumes:
            return
        vert = self.cfg.vertical_axis
        min_thick = None
        for vol in self.m.volumes:
            p = vol.params
            self.w(f"/COM, {vol.prov.guid} - {vol.prov.ifc_class} '{vol.prov.name}'")
            # working plane at the body's axis (IFC plan centre), Z vertical
            cx, cy = float(p.get("cx", 0.0)), float(p.get("cy", 0.0))
            self.w("WPCSYS,-1,0")
            if vert == "y":
                if cx or cy:
                    self.w(f"WPOFFS,{round(cx, 6):g},0,{round(cy, 6):g}")
                self.w("WPROTA,0,-90,0   ! WP Z-axis -> global Y (vertical)")
            elif cx or cy:
                self.w(f"WPOFFS,{round(cx, 6):g},{round(cy, 6):g},0")
            if vol.kind == "cylinder":
                t = p["r_outer"] - p.get("r_inner", 0.0) if p.get("r_inner", 0.0) > 0 else None
                self.w(f"CYLIND,{p.get('r_inner', 0.0):g},{p['r_outer']:g},"
                       f"{p['z_min']:g},{p['z_max']:g},0,360")
            elif vol.kind == "spherical_shell":
                t = p["r_outer"] - p["r_inner"]
                self.w(f"WPOFFS,0,0,{p['cz']:g}",
                       "WPROTA,0,90,0",
                       f"SPHERE,{p['r_inner']:g},{p['r_outer']:g},0,180",
                       "WPROTA,0,-90,0",
                       f"WPOFFS,0,0,{-p['cz']:g}")
            else:
                continue
            if t:
                min_thick = t if min_thick is None else min(min_thick, t)
        self.w("ALLSEL,ALL", "VADD,ALL")
        mat = self.m.volumes[0].material
        self.w("VSEL,ALL", f"VATT,{mat},,{type_of[self.m.volumes[0].etype]}", "VSEL,ALL", "")
        if self.cfg.mesh.containment_strict_thickness and min_thick:
            # strict mode: >= N elements across the thinnest wall (stress runs)
            esz = min(self.cfg.mesh.target_size,
                      min_thick / self.cfg.mesh.solid_through_thickness)
            self.w(f"*SET,SOLID_ESIZE,{esz:g}")

    def _entity_cms(self, by_class: dict[str, list[int]], kind: str) -> None:
        sel = "LSEL" if kind == "LINE" else "ASEL"
        for cls, ids in by_class.items():
            self.w(f"{sel},NONE")
            for i in ids:
                self.w(f"{sel},A,{kind},,{i}")
            self.w(f"CM,{_cm_name('C_', cls.upper())},{kind}")
        self.w(f"{sel},ALL", "")

    def mesh_lines(self) -> None:
        """Mesh member lines BEFORE any area-boundary line exists, so
        LMESH,ALL can never turn a slab edge into a spurious beam."""
        m = self.m
        self.w("LESIZE,ALL,MESH_SIZE")
        for mem in m.members:
            if mem.arc is not None:
                p1, p2 = m.nodes.xyz(mem.start), m.nodes.xyz(mem.end)
                chord = math.dist(p1, p2)
                half = min(1.0, chord / (2 * mem.arc.radius))
                arc_len = 2 * mem.arc.radius * math.asin(half)
                ndiv = max(self.cfg.mesh.arc_min_divisions,
                           math.ceil(arc_len / self.cfg.mesh.target_size))
                self.w(f"LESIZE,{self.member_line[mem.id]},,,{ndiv}")
        self.w("LMESH,ALL", "")

    def mesh_areas(self) -> None:
        self.w("ESIZE,MESH_SIZE", "AESIZE,ALL,MESH_SIZE", "AMESH,ALL", "")

    def mesh_volumes(self) -> None:
        if self.cfg.mesh.containment_strict_thickness:
            self.w("ESIZE,SOLID_ESIZE", "MSHAPE,1,3D", "VMESH,ALL", "")
        else:
            self.w(f"SMRTSIZE,{self.cfg.mesh.containment_smartsize}",
                   "MSHAPE,1,3D", "VMESH,ALL", "")

    def merge(self) -> None:
        self.w("NUMMRG,NODE,MERGE_TOL", "NUMMRG,KP,MERGE_TOL", "")

    def links(self, type_of: dict[str, int]) -> None:
        """Spring links (hangers) as COMBIN14 in its default 3-D longitudinal
        form: stiffness acts along the node-pair line (the rod axis), so no
        DOF mapping across the axis permutation is needed. Structure-side
        nodes are created directly (they belong to no meshed entity) and
        grounded through a CM component."""
        if not self.m.links:
            return
        tid = type_of["COMBIN14"]
        r_of: dict[float, int] = {}
        for lk in self.m.links:
            key = round(lk.k, 6)
            if key not in r_of:
                r_of[key] = len(r_of) + 1
                self.w(f"R,{r_of[key]},{lk.k:g}")
        self.w("*GET,NGRND0,NODE,0,NUM,MAX")
        for i, lk in enumerate(self.m.links, 1):
            self.w(f"/COM, {lk.prov.guid} - {lk.prov.ifc_class} '{lk.prov.name}' "
                   f"k={lk.k:g} N/m [grounded spring]")
            x, y, z = self.p(self.m.nodes.xyz(lk.n2))
            self.w(f"N,NGRND0+{i},{x:g},{y:g},{z:g}")
            self.w(f"KSEL,S,KP,,{lk.n1}", "NSLK,S", "*GET,NATT_,NODE,0,NUM,MIN",
                   f"TYPE,{tid}", f"REAL,{r_of[round(lk.k, 6)]}",
                   f"E,NATT_,NGRND0+{i}", "ALLSEL,ALL")
        self.w(f"NSEL,S,NODE,,NGRND0+1,NGRND0+{len(self.m.links)}",
               "CM,HANGER_GROUND,NODE", "D,ALL,ALL,0", "ALLSEL,ALL", "")

    def supports(self) -> None:
        for sup in self.m.supports:
            if sup.source == "heuristic:hanger-ground":
                continue                    # grounded with the spring elements
            if not sup.nodes and not sup.edges:
                continue                    # volume-level supports handled separately
            self.w(f"/COM, support '{sup.name}' [{sup.source}]")
            if sup.nodes:
                self.w("KSEL,NONE")
                for k in sup.nodes:
                    self.w(f"KSEL,A,KP,,{k}")
                self.w("NSLK,S")
            if sup.edges:
                self.w("LSEL,NONE")
                for k1, k2 in sup.edges:
                    ln = self.line_of.get((min(k1, k2), max(k1, k2)))
                    if ln is not None:
                        self.w(f"LSEL,A,LINE,,{ln}")
                if sup.nodes:
                    self.w("NSLL,A,1")
                else:
                    self.w("NSLL,S,1")
            self.w(f"CM,{_cm_name('', sup.name)},NODE",
                   f"D,ALL,{sup.dofs},0",
                   "ALLSEL,ALL", "")

    def volume_supports(self) -> None:
        """Basemat-bottom fixity for containment volumes (area-based select)."""
        base = [v for v in self.m.volumes if v.kind == "cylinder"]
        if not base or not any(s.source.startswith("heuristic:basemat") for s in self.m.supports):
            return
        zmin = min(v.params["z_min"] for v in base)
        coord = "Y" if self.cfg.vertical_axis == "y" else "Z"
        self.w(
            "/COM, support: basemat bottom face [heuristic:basemat-bottom]",
            f"NSEL,S,LOC,{coord},{zmin:g}-MERGE_TOL,{zmin:g}+MERGE_TOL",
            "CM,BASEMAT_FIX,NODE",
            "D,ALL,ALL,0",
            "ALLSEL,ALL", "",
        )

    def build(self) -> str:
        type_of_holder: dict[str, int] = {}
        self.header()
        type_of_holder = self.element_types()
        self.materials()
        self.sections()
        self.keypoints()
        if self.m.members:
            self.members(type_of_holder)
            self.mesh_lines()
        if self.m.surfaces:
            self.surfaces(type_of_holder)
            self.mesh_areas()
        if self.m.volumes:
            self.volumes(type_of_holder)
            self.mesh_volumes()
        self.merge()
        self.links(type_of_holder)
        self.supports()
        self.volume_supports()
        self.w("/COM, end of preprocessing",
               "SAVE", "FINISH")
        return "\n".join(self.lines_out) + "\n"


def write_deck(model: AnalyticalModel, config: ConversionConfig,
               path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = DeckWriter(model, config).build()
    # APDL readers are ASCII-only in practice; degrade exotic name characters
    path.write_text(text.encode("ascii", "replace").decode("ascii"), encoding="ascii")
    return path
